### ISSUE TITLE
Can not build on macOS with swift 3.0.2

### ISSUE THREAD

**Issue by zloidemon** [tris-foundation/fiber#1]
```
Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
Target: x86_64-apple-macosx10.9
```

```
public final class Channel<T> {
                   ^
/Users/vg/Devel/Tarantool/Swift/fiber/Sources/Fiber/Channel.swift:111:26: error: consecutive declarations on a line must be separated by ';'
    @_specialize(exported: true, kind: full, where T == String)
                         ^
                         ;
/Users/vg/Devel/Tarantool/Swift/fiber/Sources/Fiber/Channel.swift:111:26: error: expected declaration
    @_specialize(exported: true, kind: full, where T == String)
                         ^
/Users/vg/Devel/Tarantool/Swift/fiber/Sources/Fiber/Channel.swift:11:20: note: in declaration of 'Channel'
public final class Channel<T> {
                   ^
<unknown>:0: error: build had 1 command failures
error: exit(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/vg/Devel/Tarantool/Swift/fiber/.build/debug.yaml
```

**Comment by tonyfreeman** [comment]
Resolved in https://github.com/tris-foundation/tarantool/issues/1
